package boofcv.helper.visualize.control;

import java.awt.*;
import javax.swing.*;

/**
 Created by th on 28.07.16.
 */
public class ControlBoolean extends Control<Boolean> {
   private JCheckBox valueCheckBox;
   private JPanel panel;

   public ControlBoolean(final String name, boolean status) {
      super(name);
      SwingUtilities.invokeLater(() -> valueCheckBox.setText(name + ": "));
      SwingUtilities.invokeLater(new Runnable() {
         public void run() {
            valueCheckBox.setSelected(status);
            valueCheckBox.addActionListener(event -> controlListener.fireControlUpdated(ControlBoolean.this));
         }
      });
   }

   public Boolean getValue() {
      return valueCheckBox.isSelected();
   }

   public Component getComponent() {
      return panel;
   }

   {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    Method generated by IntelliJ IDEA GUI Designer
    >>> IMPORTANT!! <<<
    DO NOT edit this method OR call it in your code!

    @noinspection ALL */
   private void $$$setupUI$$$() {
      panel = new JPanel();
      panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
      valueCheckBox = new JCheckBox();
      valueCheckBox.setHorizontalAlignment(10);
      valueCheckBox.setHorizontalTextPosition(10);
      valueCheckBox.setText("Value:");
      panel.add(valueCheckBox, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
   }

   /**
    @noinspection ALL */
   public JComponent $$$getRootComponent$$$() { return panel; }
}
