package boofcv.helper.visualize.control;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.TitledBorder;

/**
 Created by th on 28.07.16.
 */
public class ControlBoolean extends Control<Boolean> {
   private JCheckBox valueCheckBox;
   private JPanel panel;

   public ControlBoolean(final String name, boolean status) {
      super(name);
      SwingUtilities.invokeLater(() -> ((TitledBorder) panel.getBorder()).setTitle(name));
      SwingUtilities.invokeLater(() -> {
         valueCheckBox.setSelected(status);
         valueCheckBox.addActionListener(event -> controlListener.fireControlUpdated(ControlBoolean.this));
      });
   }

   public Boolean getValue() {
      return valueCheckBox.isSelected();
   }

   public Component getComponent() {
      return panel;
   }

   {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    Method generated by IntelliJ IDEA GUI Designer
    >>> IMPORTANT!! <<<
    DO NOT edit this method OR call it in your code!

    @noinspection ALL */
   private void $$$setupUI$$$() {
      panel = new JPanel();
      panel.setLayout(new GridBagLayout());
      valueCheckBox = new JCheckBox();
      valueCheckBox.setHorizontalAlignment(10);
      valueCheckBox.setHorizontalTextPosition(10);
      valueCheckBox.setText("Value:");
      GridBagConstraints gbc;
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 0;
      gbc.weightx = 1.0;
      gbc.weighty = 1.0;
      gbc.anchor = GridBagConstraints.WEST;
      panel.add(valueCheckBox, gbc);
   }

   /**
    @noinspection ALL */
   public JComponent $$$getRootComponent$$$() { return panel; }
}
