package boofcv.helper.visualize.control;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.TitledBorder;

/**
 Created by th on 28.07.16.
 */
public class ControlList<T> extends Control<T> {
   private final DefaultComboBoxModel<T> model;
   private JPanel panel;
   private JComboBox<T> comboBox;
   //private JLabel label;

   public ControlList(final String name, T... list) {
      super(name);
      //SwingUtilities.invokeLater(() -> label.setText(name + ": "));
      SwingUtilities.invokeLater(() -> comboBox.addActionListener(event -> controlListener.fireControlUpdated(ControlList.this)));
      model = new DefaultComboBoxModel<>();
      for (T t : list) {
         model.addElement(t);
      }
      comboBox.setModel(model);
      SwingUtilities.invokeLater(() -> {
         ((TitledBorder)panel.getBorder()).setTitle(name);
         panel.repaint();
      });
   }

   public T getValue() {
      return (T)model.getSelectedItem();
   }

   public Component getComponent() {
      return panel;
   }

   {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    Method generated by IntelliJ IDEA GUI Designer
    >>> IMPORTANT!! <<<
    DO NOT edit this method OR call it in your code!

    @noinspection ALL */
   private void $$$setupUI$$$() {
      panel = new JPanel();
      panel.setLayout(new GridBagLayout());
      panel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Label"));
      comboBox = new JComboBox();
      GridBagConstraints gbc;
      gbc = new GridBagConstraints();
      gbc.gridx = 0;
      gbc.gridy = 0;
      gbc.weightx = 1.0;
      gbc.anchor = GridBagConstraints.WEST;
      gbc.fill = GridBagConstraints.HORIZONTAL;
      panel.add(comboBox, gbc);
   }

   /**
    @noinspection ALL */
   public JComponent $$$getRootComponent$$$() { return panel; }
}
